/**
 * MIDI Commands
 **/

// NAMES
const NOTE_OFF_COMMAND_NAME = "NOTE OFF"
const NOTE_ON_COMMAND_NAME = "NOTE ON"
const CONTROL_CHANGE_COMMAND_NAME = "CONTROL CHANGE"
const PROGRAM_CHANGE_COMMAND_NAME = "PROGRAM CHANGE"
const UNKNOWN_COMMAND_NAME = "UNKNOWN"

// MIN AND MAX
const NOTE_OFF_COMMAND_MIN = 128
const NOTE_OFF_COMMAND_MAX = 143
const NOTE_ON_COMMAND_MIN = 144
const NOTE_ON_COMMAND_MAX = 159
const CONTROL_CHANGE_COMMAND_MIN = 176
const CONTROL_CHANGE_COMMAND_MAX = 191
const PROGRAM_CHANGE_COMMAND_MIN = 192
const PROGRAM_CHANGE_COMMAND_MAX = 207

export default {
	// MIDI Commands

	// NAMES
	NOTE_OFF_COMMAND_NAME,
	NOTE_ON_COMMAND_NAME,
	CONTROL_CHANGE_COMMAND_NAME,
	PROGRAM_CHANGE_COMMAND_NAME,
	UNKNOWN_COMMAND_NAME,

	// MIN AND MAX
	NOTE_OFF_COMMAND_MIN,
	NOTE_OFF_COMMAND_MAX,
	NOTE_ON_COMMAND_MIN,
	NOTE_ON_COMMAND_MAX,
	CONTROL_CHANGE_COMMAND_MIN,
	CONTROL_CHANGE_COMMAND_MAX,
	PROGRAM_CHANGE_COMMAND_MIN,
	PROGRAM_CHANGE_COMMAND_MAX,
}