const TENS_PLACE_AZ_MESSAGE_CODE = 109
const TENS_PLACE_HEX_MESSAGE_CODE = 113
const TENS_PLACE_DEFAULT = 16
const ONES_PLACE_AZ_MESSAGE_CODE = 110
const ONES_PLACE_HEX_MESSAGE_CODE = 114
const ONES_PLACE_DEFAULT = 15

/**
 * SEVEN-SEGMENT DISPLAY
 **/
const ALPHABET_CHARACTER_LIST = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z',' ']
const HEX_CHARACTER_LIST = ['0','1','2','3','4','5','6','7','8','9','0','A','B','C','D','E','F',' ']


/**
 * MIDI OUTPUT
 **/

// EVENT NAMES
const PRESS_NAME = "PRESS"
const RELEASE_NAME = "RELEASE"
const MIDI_OUTPUT_EVENT_NAMES_LIST = [
  PRESS_NAME,
  RELEASE_NAME,
]

// EVENT VALUES
const PRESS_VALUE = 104
const RELEASE_VALUE = 105
const MIDI_OUTPUT_EVENT_VALUES_LIST = [
  PRESS_VALUE,
  RELEASE_VALUE,
]

// BUTTON NAMES
const ONE_NAME = "BUTTON 1"
const TWO_NAME = "BUTTON 2"
const THREE_NAME = "BUTTON 3"
const FOUR_NAME = "BUTTON 4"
const FIVE_NAME = "BUTTON 5"
const SIX_NAME = "BUTTON 6"
const SEVEN_NAME = "BUTTON 7"
const EIGHT_NAME = "BUTTON 8"
const NINE_NAME = "BUTTON 9"
const TEN_NAME = "BUTTON 10"
const UP_NAME = "UP"
const DOWN_NAME = "DOWN"
const MIDI_OUTPUT_BUTTON_NAMES_LIST = [
  ONE_NAME,
  TWO_NAME,
  THREE_NAME,
  FOUR_NAME,
  FIVE_NAME,
  SIX_NAME,
  SEVEN_NAME,
  EIGHT_NAME,
  NINE_NAME,
  TEN_NAME,
  UP_NAME,
  DOWN_NAME,
]

// BUTTON VALUES
const ONE_VALUE = 1
const TWO_VALUE = 2
const THREE_VALUE = 3
const FOUR_VALUE = 4
const FIVE_VALUE = 5
const SIX_VALUE = 6
const SEVEN_VALUE = 7
const EIGHT_VALUE = 8
const NINE_VALUE = 9
const TEN_VALUE = 0
const UP_VALUE = 10
const DOWN_VALUE = 11
const MIDI_OUTPUT_BUTTON_VALUES_LIST = [
  ONE_VALUE,
  TWO_VALUE,
  THREE_VALUE,
  FOUR_VALUE,
  FIVE_VALUE,
  SIX_VALUE,
  SEVEN_VALUE,
  EIGHT_VALUE,
  NINE_VALUE,
  TEN_VALUE,
  UP_VALUE,
  DOWN_VALUE,
]

export default {
  // SEVEN-SEGMENT DISPLAY
  ALPHABET_CHARACTER_LIST,
  HEX_CHARACTER_LIST,

  // MIDI OUTPUT

  // EVENT NAMES
  PRESS_NAME,
  RELEASE_NAME,
  MIDI_OUTPUT_EVENT_NAMES_LIST,

  // EVENT VALUES
  PRESS_VALUE,
  RELEASE_VALUE,
  MIDI_OUTPUT_EVENT_VALUES_LIST,

  // BUTTON NAMES
  ONE_NAME,
  TWO_NAME,
  THREE_NAME,
  FOUR_NAME,
  FIVE_NAME,
  SIX_NAME,
  SEVEN_NAME,
  EIGHT_NAME,
  NINE_NAME,
  TEN_NAME,
  UP_NAME,
  DOWN_NAME,
  MIDI_OUTPUT_BUTTON_NAMES_LIST,

  // BUTTON VALUES
  ONE_VALUE,
  TWO_VALUE,
  THREE_VALUE,
  FOUR_VALUE,
  FIVE_VALUE,
  SIX_VALUE,
  SEVEN_VALUE,
  EIGHT_VALUE,
  NINE_VALUE,
  TEN_VALUE,
  UP_VALUE,
  DOWN_VALUE,
  MIDI_OUTPUT_BUTTON_VALUES_LIST,
}